#!/usr/bin/env node

(function(){
  var zmq = require('zmq');

  var service = zmq.socket('rep');
  service.on('message', function(){
    var frames = Array.apply(null, arguments);
    console.log("Service received: %s", frames);
    frames[1] = "pong";
    service.send(frames);
  });
  service.bind('inproc://socket');

  var number = 1;
  var client = zmq.socket('req');
  client.on('message', function(){
    var frames = Array.apply(null, arguments);
    console.log("Client received: %s", frames);
    setTimeout(function(){
      client.send([number++, "ping"]);
    }, 500);
  });
  client.connect('inproc://socket');

  console.log("Started clients & server");
  client.send([number++, "ping"]);
})();
